/*
 * Copyright © 2022-present the iocgo authors. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ioc

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestNormalizeRawOptions(t *testing.T) {
	if got := NormalizeRawOptions(nil); len(got) != 2 || got[0] != "register" || got[1] != "paths=./..." {
		t.Fatalf("NormalizeRawOptions(nil) = %#v", got)
	}
	if got := NormalizeRawOptions([]string{"paths=./pkg"}); len(got) != 2 || got[0] != "paths=./pkg" || got[1] != "register" {
		t.Fatalf("NormalizeRawOptions(one) = %#v", got)
	}
}

func TestPublicRunGeneratesAnnotatedPackage(t *testing.T) {
	sourceDir := filepath.Clean(filepath.Join("..", "..", "cmd", "ioctl", "di", "testdata", "simple"))
	tempDir, err := os.MkdirTemp(".", "gentest-")
	if err != nil {
		t.Fatalf("MkdirTemp() error = %v", err)
	}
	t.Cleanup(func() {
		_ = os.RemoveAll(tempDir)
	})
	entries, err := os.ReadDir(sourceDir)
	if err != nil {
		t.Fatalf("ReadDir() error = %v", err)
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		content, err := os.ReadFile(filepath.Join(sourceDir, entry.Name()))
		if err != nil {
			t.Fatalf("ReadFile(%s) error = %v", entry.Name(), err)
		}
		if err := os.WriteFile(filepath.Join(tempDir, entry.Name()), content, 0o644); err != nil {
			t.Fatalf("WriteFile(%s) error = %v", entry.Name(), err)
		}
	}

	if err := Run([]string{"register", "paths=" + filepath.ToSlash(tempDir)}); err != nil {
		t.Fatalf("Run() error = %v", err)
	}

	generatedPath := filepath.Join(tempDir, "zz_generated.iocgo.go")
	content, err := os.ReadFile(generatedPath)
	if err != nil {
		t.Fatalf("ReadFile(generated) error = %v", err)
	}
	generated := string(content)

	checks := []string{
		"// Code generated by iocgo ctl (ioctl). DO NOT EDIT.",
		"func RegisterIocgoBeans(reg iocgo.Registry) error",
		"iocgo.Define[*Repo]",
		"iocgo.Define[*Service]",
	}
	for _, check := range checks {
		if !strings.Contains(generated, check) {
			t.Fatalf("expected generated content to contain %q\n%s", check, generated)
		}
	}
}
