/*
 * Copyright © 2022-present the iocgo authors. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package di

import (
	"strings"
	"testing"

	"sigs.k8s.io/controller-tools/pkg/loader"
	"sigs.k8s.io/controller-tools/pkg/markers"
)

func TestGeneratorHandlesAnnotatedPackage(t *testing.T) {
	roots, err := loader.LoadRoots("./testdata/simple")
	if err != nil {
		t.Fatalf("load roots: %v", err)
	}
	if len(roots) != 1 {
		t.Fatalf("expected a single root package, got %d", len(roots))
	}

	registry := &markers.Registry{}
	generator := Generator{}
	if err := generator.RegisterMarkers(registry); err != nil {
		t.Fatalf("register markers: %v", err)
	}

	iocCtx := IocGoGenerationContext{
		Collector: &markers.Collector{Registry: registry},
		Checker:   &loader.TypeChecker{},
	}
	out := iocCtx.handlePackage(roots[0])
	if len(out) == 0 {
		t.Fatalf("expected generated output")
	}
	content := string(out)

	checks := []string{
		"// Code generated by iocgo ctl (ioctl). DO NOT EDIT.",
		"// Generated at:",
		"// Source package:",
		"func RegisterIocgoBeans(reg iocgo.Registry) error",
		"iocgo.Define[*Repo]",
		"iocgo.Define[*AppConfiguration]",
		"iocgo.Define[*Service]",
		"iocgo.RegisterBeans",
	}
	for _, check := range checks {
		if !strings.Contains(content, check) {
			t.Fatalf("expected generated content to contain %q\n%s", check, content)
		}
	}
}

func TestGeneratorSupportsNemoEnvironmentConvention(t *testing.T) {
	roots, err := loader.LoadRoots("./testdata/nemoenv")
	if err != nil {
		t.Fatalf("load roots: %v", err)
	}
	if len(roots) != 1 {
		t.Fatalf("expected a single root package, got %d", len(roots))
	}

	registry := &markers.Registry{}
	generator := Generator{}
	if err := generator.RegisterMarkers(registry); err != nil {
		t.Fatalf("register markers: %v", err)
	}

	iocCtx := IocGoGenerationContext{
		Collector: &markers.Collector{Registry: registry},
		Checker:   &loader.TypeChecker{},
	}
	out := iocCtx.handlePackage(roots[0])
	if len(out) == 0 {
		t.Fatalf("expected generated output")
	}
	content := string(out)

	checks := []string{
		"// Code generated by iocgo ctl (ioctl). DO NOT EDIT.",
		"starterNemo \"github.com/photowey/iocgo/pkg/starters/nemo\"",
		"iocgo.Define[*AppConfiguration]",
		"iocgo.Define[*AppInfo]",
		"env, err := iocgo.Get[starterNemo.Environment](ctx, resolver)",
	}
	for _, check := range checks {
		if !strings.Contains(content, check) {
			t.Fatalf("expected generated content to contain %q\n%s", check, content)
		}
	}
}

func TestGeneratorSupportsBindPrefixConvention(t *testing.T) {
	roots, err := loader.LoadRoots("./testdata/bindcfg")
	if err != nil {
		t.Fatalf("load roots: %v", err)
	}
	if len(roots) != 1 {
		t.Fatalf("expected a single root package, got %d", len(roots))
	}

	registry := &markers.Registry{}
	generator := Generator{}
	if err := generator.RegisterMarkers(registry); err != nil {
		t.Fatalf("register markers: %v", err)
	}

	iocCtx := IocGoGenerationContext{
		Collector: &markers.Collector{Registry: registry},
		Checker:   &loader.TypeChecker{},
	}
	out := iocCtx.handlePackage(roots[0])
	if len(out) == 0 {
		t.Fatalf("expected generated output")
	}
	content := string(out)

	checks := []string{
		"// Code generated by iocgo ctl (ioctl). DO NOT EDIT.",
		"starterNemo \"github.com/photowey/iocgo/pkg/starters/nemo\"",
		"iocgo.Define[*FeatureConfig]",
		"iocgo.Define[*AppConfiguration]",
		"binder, err := iocgo.Get[*starterNemo.Binder](ctx, resolver, starterNemo.BinderBeanName)",
		"if err := binder.Bind(\"app.feature\", bean); err != nil {",
		"if err := binder.Bind(\"app.info\", bean); err != nil {",
		"starterNemo.WrapBindError(",
	}
	for _, check := range checks {
		if !strings.Contains(content, check) {
			t.Fatalf("expected generated content to contain %q\n%s", check, content)
		}
	}
}

func TestGeneratorRejectsConfigurationPropertiesWithoutPrefix(t *testing.T) {
	roots, err := loader.LoadRoots("./testdata/invalidcfg")
	if err != nil {
		t.Fatalf("load roots: %v", err)
	}

	registry := &markers.Registry{}
	generator := Generator{}
	if err := generator.RegisterMarkers(registry); err != nil {
		t.Fatalf("register markers: %v", err)
	}

	iocCtx := IocGoGenerationContext{
		Collector: &markers.Collector{Registry: registry},
		Checker:   &loader.TypeChecker{},
	}
	out := iocCtx.handlePackage(roots[0])
	if len(out) != 0 {
		t.Fatalf("expected no generated output for invalid configuration-properties usage")
	}
	if len(roots[0].Errors) == 0 {
		t.Fatalf("expected package errors for missing configuration-properties prefix")
	}
	if !strings.Contains(roots[0].Errors[0].Msg, "configuration-properties") {
		t.Fatalf("expected configuration-properties error, got %+v", roots[0].Errors)
	}
}

func TestGeneratorRejectsConfigurationPropertiesWithoutBeanRole(t *testing.T) {
	roots, err := loader.LoadRoots("./testdata/invalidcfgkind")
	if err != nil {
		t.Fatalf("load roots: %v", err)
	}

	registry := &markers.Registry{}
	generator := Generator{}
	if err := generator.RegisterMarkers(registry); err != nil {
		t.Fatalf("register markers: %v", err)
	}

	iocCtx := IocGoGenerationContext{
		Collector: &markers.Collector{Registry: registry},
		Checker:   &loader.TypeChecker{},
	}
	out := iocCtx.handlePackage(roots[0])
	if len(out) != 0 {
		t.Fatalf("expected no generated output for invalid configuration-properties role")
	}
	if len(roots[0].Errors) == 0 {
		t.Fatalf("expected package errors for invalid configuration-properties role")
	}
	if !strings.Contains(roots[0].Errors[0].Msg, "neither a component nor a configuration") {
		t.Fatalf("expected component/configuration role error, got %+v", roots[0].Errors)
	}
}
